name = "apotheon-csp-report-handler"
account_id = "00000000000000000000000000000000"
main = "workers/csp-report-handler.ts"
compatibility_date = "2024-10-08"
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"

[[routes]]
pattern = "csp.apotheon.ai/report"
custom_domain = true

# The default configuration above deploys the CSP ingestion Worker. Additional
# Workers are represented as dedicated `env.*` sections below so Wrangler can
# deploy each entry point by invoking `wrangler deploy --env <name>`.

[env.contact_intake]
name = "apotheon-contact-intake"
main = "workers/contact.ts"
usage_model = "standard"
compatibility_date = "2024-10-08"
migrations_dir = "workers/migrations/contact"

[[env.contact_intake.routes]]
pattern = "apotheon.ai/api/contact"
custom_domain = true

[[env.contact_intake.routes]]
pattern = "contact.apotheon.ai/*"
custom_domain = true

[[env.contact_intake.kv_namespaces]]
binding = "CONTACT_RATE_LIMIT"
id = "00000000000000000000000000000000"
preview_id = "11111111111111111111111111111111"

[[env.contact_intake.d1_databases]]
binding = "CONTACT_AUDIT_DB"
database_name = "apotheon-contact"
database_id = "00000000-0000-0000-0000-000000000000"

[env.contact_intake.vars]
CONTACT_BLOCKLIST = ""
CONTACT_ALLOWLIST = ""

[env.whitepaper_delivery]
name = "apotheon-whitepaper-delivery"
main = "workers/whitepapers.ts"
usage_model = "standard"
compatibility_date = "2024-10-08"
migrations_dir = "workers/migrations/whitepapers"

[[env.whitepaper_delivery.routes]]
pattern = "apotheon.ai/api/whitepapers"
custom_domain = true

[[env.whitepaper_delivery.kv_namespaces]]
binding = "WHITEPAPER_RATE_LIMIT"
id = "00000000000000000000000000000000"
preview_id = "11111111111111111111111111111111"

[[env.whitepaper_delivery.d1_databases]]
binding = "WHITEPAPER_AUDIT_DB"
database_name = "apotheon-whitepapers"
database_id = "00000000-0000-0000-0000-000000000001"

[[env.whitepaper_delivery.r2_buckets]]
binding = "WHITEPAPER_ASSETS"
bucket_name = "apotheon-whitepapers"
preview_bucket_name = "apotheon-whitepapers-preview"

[env.whitepaper_delivery.vars]
WHITEPAPER_BLOCKLIST = ""
WHITEPAPER_ALLOWLIST = ""
WHITEPAPER_SIGNING_TTL_SECONDS = "900"
