/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/bwccum.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const BwccumIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'BWCCUM autonomous control mesh icon', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'BwccumIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <circle cx="12" cy="12" r="8.25" stroke="#0ea5e9" />
        <path stroke="#1e3a8a" d="M8.25 12a3.75 3.75 0 1 0 7.5 0 3.75 3.75 0 1 0-7.5 0" />
        <path stroke="#1d4ed8" d="M5.75 5.75 9 9m6 6 3.25 3.25" />
        <path stroke="#2563eb" d="M5.75 18.25 9 15m6-6 3.25-3.25" />
        <circle cx="12" cy="12" r="1.4" stroke="#38bdf8" />
      </svg>
    );
  },
);

BwccumIcon.displayName = 'BwccumIcon';
