/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/clio.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const ClioIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Clio brand logomark', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'ClioIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <rect width="6.5" height="14.5" x="4.75" y="4.75" stroke="#312e81" rx="1.6" />
        <rect width="6.5" height="14.5" x="12.75" y="4.75" stroke="#312e81" rx="1.6" />
        <path stroke="#4338ca" d="M12 6.25v10.5l-1.5-1.25m-3-6h2.25m5.75 0h2.25" />
      </svg>
    );
  },
);

ClioIcon.displayName = 'ClioIcon';
