/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/hermes.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const HermesIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Hermes orchestration emblem', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'HermesIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0f172a" d="M12 4.5v15" />
        <path
          stroke="#0ea5e9"
          d="M8.5 7.75c1.2-1.1 2.6-1.1 3.5 0s2.3 1.1 3.5 0M8.5 12c1.2-1.1 2.6-1.1 3.5 0s2.3 1.1 3.5 0"
        />
        <path stroke="#312e81" d="m6 6.25 2.5 1.5L6 9.25m12-3-2.5 1.5 2.5 1.5m-9 9.5h6" />
      </svg>
    );
  },
);

HermesIcon.displayName = 'HermesIcon';
