/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-energy.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryEnergyIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Energy industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryEnergyIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0ea5e9" d="m12 4.5-2.25 5h-5l4 2.5-1.5 4.75L12 14.5l4.75 2.25-1.5-4.75 4-2.5h-5Z" />
        <path stroke="#f97316" d="M12 10.5 10.75 13h2L12 15.5" />
      </svg>
    );
  },
);

IndustryEnergyIcon.displayName = 'IndustryEnergyIcon';
