/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-public-sector.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryPublicSectorIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Public sector industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryPublicSectorIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#312e81" d="M12 4.25a4.5 4.5 0 0 1 4.5 4.5v1h-9v-1a4.5 4.5 0 0 1 4.5-4.5" />
        <path stroke="#0ea5e9" d="M6.25 12.25h11.5l-1 6.5h-9.5Z" />
        <path stroke="#4338ca" d="M12 11.5s2 1.25 4 1.25c0 3.25-1.5 5.5-4 6.75-2.5-1.25-4-3.5-4-6.75 2 0 4-1.25 4-1.25m0 2.5v2" />
      </svg>
    );
  },
);

IndustryPublicSectorIcon.displayName = 'IndustryPublicSectorIcon';
