/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-military.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryMilitaryIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Military industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryMilitaryIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path
          stroke="#0f172a"
          d="m12 3.5 7 2.75v5.25c0 4.45-3 7.55-7 8.75-4-1.2-7-4.3-7-8.75V6.25z"
        />
        <path
          stroke="#4338ca"
          d="m12 8.25 1 1.95 2.15.3L13.6 12l.37 2.1L12 12.95l-1.97 1.15.37-2.1-1.55-1.5 2.15-.3z"
        />
        <path stroke="#0ea5e9" d="M8.5 14.75c1 1.4 2.2 2.3 3.5 2.7 1.3-.4 2.5-1.3 3.5-2.7" />
      </svg>
    );
  },
);

IndustryMilitaryIcon.displayName = 'IndustryMilitaryIcon';
