/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-government.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryGovernmentIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Government services industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryGovernmentIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path
          stroke="#0ea5e9"
          d="M12 4.5c-3.2 0-5.75 2.55-5.75 5.7v.8h11.5v-.8c0-3.15-2.55-5.7-5.75-5.7"
        />
        <path stroke="#0f172a" d="M7.5 11v6.5" />
        <path stroke="#4338ca" d="M10.5 11v6.5m3-6.5v6.5" />
        <path stroke="#0f172a" d="M16.5 11v6.5" />
        <path stroke="#0ea5e9" d="M6 17.5h12" />
        <path stroke="#0f172a" d="M5.25 19.5h13.5" />
      </svg>
    );
  },
);

IndustryGovernmentIcon.displayName = 'IndustryGovernmentIcon';
