/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-intelligence.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryIntelligenceIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Intelligence industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryIntelligenceIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <circle cx="12" cy="7" r="2.25" stroke="#4338ca" />
        <circle cx="7" cy="14.5" r="1.85" stroke="#0ea5e9" />
        <circle cx="17" cy="15.5" r="1.85" stroke="#0ea5e9" />
        <path stroke="#0f172a" d="m10.5 8.8-2.4 3.1m5.4-3.1 2.3 3.4" />
        <path stroke="#4338ca" d="m8.5 16.35 6.75.9" />
        <path stroke="#0ea5e9" d="M6.5 5.5c1.4-1.9 3.6-3 5.5-3s4.1 1.1 5.5 3" />
      </svg>
    );
  },
);

IndustryIntelligenceIcon.displayName = 'IndustryIntelligenceIcon';
