/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-law.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryLawIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Legal services industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryLawIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0f172a" d="M12 4.5V16" />
        <path stroke="#0ea5e9" d="M6 7.75h12" />
        <path stroke="#4338ca" d="M8.5 7.75 6.5 12h4z" />
        <path stroke="#0f172a" d="M8.5 7.75v-2" />
        <path stroke="#4338ca" d="m15.5 7.75-2 4.25h4z" />
        <path stroke="#0f172a" d="M15.5 7.75v-2" />
        <path stroke="#0ea5e9" d="M7.5 18.5h9" />
        <path stroke="#0f172a" d="M9.5 18.5v1.75h5V18.5" />
      </svg>
    );
  },
);

IndustryLawIcon.displayName = 'IndustryLawIcon';
