/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-healthcare.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryHealthcareIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Healthcare industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryHealthcareIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0ea5e9" d="M10.25 5.25h3.5v3.5h3.5v3.5h-3.5v3.5h-3.5v-3.5h-3.5v-3.5h3.5Z" />
        <path stroke="#4338ca" d="M5 13.5h2.25l1-2.5 2 4.75 2.25-5.5L14 13.5h5" />
      </svg>
    );
  },
);

IndustryHealthcareIcon.displayName = 'IndustryHealthcareIcon';
