/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/industry-finance.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const IndustryFinanceIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Finance industry glyph', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'IndustryFinanceIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0f172a" d="M4.5 5.75v12.5h15" />
        <rect width="2.5" height="3.25" x="6.5" y="13" stroke="#0ea5e9" rx=".6" />
        <rect width="2.5" height="5.75" x="10.5" y="10.5" stroke="#0ea5e9" rx=".6" />
        <rect width="2.5" height="8.25" x="14.5" y="8" stroke="#0ea5e9" rx=".6" />
        <path stroke="#4338ca" d="m6 11 2.25-2.25L11 12l3.25-4 4.25 3" />
      </svg>
    );
  },
);

IndustryFinanceIcon.displayName = 'IndustryFinanceIcon';
