/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/mnemosyne.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const MnemosyneIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Mnemosyne memory seal', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'MnemosyneIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <circle cx="12" cy="12" r="7.25" stroke="#312e81" />
        <circle cx="12" cy="12" r="3.25" stroke="#4338ca" />
        <path stroke="#0ea5e9" d="M12 4.75V3m0 18v-1.75M4.75 12H3m18 0h-1.75" />
        <circle cx="12" cy="3" r=".85" fill="#0ea5e9" />
        <circle cx="12" cy="21" r=".85" fill="#0ea5e9" />
        <circle cx="3" cy="12" r=".85" fill="#0ea5e9" />
        <circle cx="21" cy="12" r=".85" fill="#0ea5e9" />
      </svg>
    );
  },
);

MnemosyneIcon.displayName = 'MnemosyneIcon';
