/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/morpheus.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const MorpheusIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'Morpheus adaptive intelligence icon', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'MorpheusIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0ea5e9" d="M10.75 5.25a6 6 0 1 0 6 9.5 6.25 6.25 0 1 1-6-9.5" />
        <path stroke="#4338ca" d="M6.75 13.5c1.25-.9 2.75-.9 4 0s2.75.9 4 0" />
        <path stroke="#312e81" d="M7.75 16.25c.95-.7 2.2-.7 3.15 0s2.2.7 3.15 0" />
        <circle cx="15.75" cy="7.5" r="1.25" stroke="#4338ca" />
      </svg>
    );
  },
);

MorpheusIcon.displayName = 'MorpheusIcon';
