/**
 * Auto-generated by scripts/brand/build-icons.mjs.
 * DO NOT edit directly—edit the source in assets/brand-icons/raw/themis.svg instead.
 */
import { forwardRef } from 'react';

import type { SVGProps } from 'react';

type IconProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {
  /** Accessible title for screen readers. Provide "" to mark as decorative. */
  title?: string;
  /** Deterministic title id allows aria-labelledby composition. */
  titleId?: string;
};

export const ThemisIcon = forwardRef<SVGSVGElement, IconProps>(
  ({ title = 'THEMIS governance sigil', titleId, ...props }, ref) => {
    const labelledBy = title ? (titleId ?? 'ThemisIconTitle') : undefined;

    return (
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="1.5"
        viewBox="0 0 24 24"
        focusable="false"
        ref={ref}
        aria-hidden={title ? undefined : true}
        aria-labelledby={title ? labelledBy : undefined}
        role="img"
        {...props}
      >
        {title ? <title id={labelledBy}>{title}</title> : null}
        <path stroke="#0f172a" d="M12 4.25v14.5" />
        <path stroke="#312e81" d="M8 6.75h8" />
        <path stroke="#4338ca" d="M7 6.75 5.25 11a2.25 2.25 0 0 0 4.5 0zm10 0L15.25 11a2.25 2.25 0 0 0 4.5 0z" />
        <path stroke="#0f172a" d="M8.5 19.75h7" />
      </svg>
    );
  },
);

ThemisIcon.displayName = 'ThemisIcon';
