/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

// React JSX support for island components lives here to guarantee
// enterprise teams get full IntelliSense out of the box.
declare namespace App {
  interface Locals {
    /**
     * Nonce generated by `securityMiddleware`. Inline `<script>`/`<style>` tags
     * can reference this value to stay aligned with the active CSP header.
     */
    cspNonce?: string;
  }
}
