/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />
/// <reference types="vitest" />
/// <reference types="@playwright/test" />

declare module 'astro/dist/runtime/server/render/index.js';
declare module '@testing-library/react';
declare module '@testing-library/user-event';
declare module 'vitest/config';
declare module 'vitest';
declare module '*.astro';
declare module '@radix-ui/react-dialog';

declare global {
  namespace App {
    interface Locals {
      /**
       * Nonce generated by `securityMiddleware`. Inline `<script>`/`<style>` tags
       * can reference this value to stay aligned with the active CSP header.
       */
      cspNonce?: string;
    }
  }

  interface ImportMetaEnv {
    readonly PUBLIC_CONTACT_ENDPOINT: string;
    readonly PUBLIC_TURNSTILE_SITE_KEY: string;
    readonly PUBLIC_OG_IMAGE_WORKER?: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  interface Window {
    dataLayer?: unknown[];
    turnstile?: {
      render(
        container: string | HTMLElement,
        options: {
          sitekey: string;
          callback: (token: string) => void;
          'error-callback'?: () => void;
          'expired-callback'?: () => void;
          appearance?: 'always' | 'execute' | 'interaction-only';
        },
      ): string;
      reset(widgetId?: string): void;
    };
    __CONTACT_FORM_SET_TOKEN__?: (value: string) => void;
  }
}

export {};
